development: &default
  adapter: postgresql
  database: openimg_development
  encoding: utf8
  min_messages: warning
  pool: <%%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000
  host:

test:
  <<: *default
  database: openimg_test
