development: &default
  adapter: postgresql
  database: openimg_development
  encoding: utf8
  timeout: 5000
  host: localhost
  username: main
  password: doot

test:
  <<: *default
  database: openimg_test
